image: node:latest
stages:
  - build
  - deploy

# build_app:
#   stage: build
#   script:
#     - npm run build
#   extends: .dependencies_cache

build:
  stage: build
  image: ghcr.io/gperdomor/nx-docker:16.3-alpine
  services:
    - docker:20.10.7-dind
  variables:
    GIT_DEPTH: 0
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - npm i
    #- echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    #- docker run --privileged --rm tonistiigi/binfmt --install all # required for multi-platform build
    - docker buildx create --use
    - npm run affected:output:plain
    - npm run affected:ci:build
    - npm run affected:ci:docker