apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-dinivas
  name: postgres-dinivas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-dinivas
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-dinivas
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dinivas
            - name: POSTGRES_PASSWORD
              value: Pa55W0rd
            - name: POSTGRES_USER
              value: dinivas
          image: postgres
          name: postgres-dinivas
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-dinivas-data
      restartPolicy: Always
      volumes:
        - name: postgres-dinivas-data
          persistentVolumeClaim:
            claimName: postgres-dinivas-data
status: {}
