apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-keycloak
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-keycloak
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: keycloak
          image: postgres:9.5
          name: postgres-keycloak
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-keycloak-data
      restartPolicy: Always
      volumes:
        - name: postgres-keycloak-data
          persistentVolumeClaim:
            claimName: postgres-keycloak-data
status: {}
