apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: terraform-worker
  name: terraform-worker
spec:
  ports:
    - name: "3334"
      port: 3334
      targetPort: 3334
  selector:
    io.kompose.service: terraform-worker
status:
  loadBalancer: {}
