apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: terraform-worker
  name: terraform-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: terraform-worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: terraform-worker
    spec:
      containers:
        - env:
            - name: PORT
              value: "3334"
          image: dinivas/terraform-worker:latest
          name: terraform-worker
          ports:
            - containerPort: 3334
          resources: {}
          volumeMounts:
            - mountPath: /config.yml
              name: terraform-worker-claim0
      restartPolicy: Always
      volumes:
        - name: terraform-worker-claim0
          persistentVolumeClaim:
            claimName: terraform-worker-claim0
status: {}
