dinivas:
  production: false
  api:
    url: 'http://api:3333/api/v1'
  tasks:
    redis:
      host: redis
      port: 6379
  cloud_providers:
    digitalocean:
      api_uses_snapshots: true
  terraform:
    min_required_version: '0.15.5'
    state:
      http_address: 'http://api:3333/api/v1/terraform/state'
      username: dinivas
      password: Pa55w0rd!
      http_timeout: 5000
      http_max_redirects: 5
    init:
      verbose: false
    plan:
      verbose: false
    apply:
      verbose: false
    destroy:
      verbose: false
    modules:
      - name: project_base
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-project-base
      - name: project_instance
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-project-instance
      - name: jenkins
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-jenkins
      - name: consul
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-consul
      - name: keypair
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-keypair
      - name: rabbitmq
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-rabbitmq
      - name: flavor
        type: git
        provider: openstack
        url: github.com/dinivas/terraform-openstack-flavor
      - name: project_base
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-project-base
      - name: project_instance
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-project-instance
      - name: jenkins
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-jenkins
      - name: consul
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-consul
      - name: keypair
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-keypair
      - name: rabbitmq
        type: git
        provider: digitalocean
        url: github.com/dinivas/terraform-digitalocean-rabbitmq
