dinivas:
  production: false
  terraform:
    min_required_version: '0.12.2'
    debug_command_outputs: false
    state:
      username: dinivas
      password: Pa55w0rd!
    modules:
      - name: project_base
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-project-base.git
      - name: keypair
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-keypair.git
  keycloak:
    config:
      realm: 'dinivas'
      bearer-only: true
      auth-server-url: 'http://auth.dinivas.serveo.net/auth'
      ssl-required: 'external'
      resource: 'dinivas-api'
      verify-token-audience: true
      credentials:
        secret: '60de3dca-6c42-42c3-b542-28ca5feb7fc7'
      confidential-port: 0
      policy-enforcer:
    admin:
      username: admin
      password: password
